services:
  db:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: todos
      POSTGRES_PASSWORD: terepiim
      POSTGRES_USER: postgres
    restart: always

  backend:
    build: ./todo-backend
    container_name: testapp_container
    ports:
      - "8080:8080"
    environment:
      db-url: jdbc:postgresql://db:5432/todos
      db-username: postgres
      db-password: terepiim
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./todo-frontend
    container_name: frontend_container
    ports:
      - "3000:5173" # Maps port 3000 on your machine to Vite's dev server
    environment:
      VITE_BACKEND_URL: http://backend:8080 # The backend container's name and port
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
